# Set to true to add reviewers to PRs
addReviewers: true

# Set to 'author' to add PR's author as an assignee
addAssignees: author

# A list of reviewers to be added to PRs (GitHub username)
reviewers:
  - RyderBelserion
  
# A number of reviewers added to the PR
# Set 0 to add all the reviewers (default: 0)
numberOfReviewers: 1

# A list of assignees, overrides reviewers if set
assignees:
  - RyderBelserion
  
# A number of assignees to add to the PRs
# Set to 0 to add all the assignees.
# Uses numberOfReviewers if unset.
numberOfAssignees: 0

# A list of keywords to be skipped the process if PR's title include it
skipKeywords:
  - wip