#file: noinspection YAMLSchemaValidation
name: ChatManager
main: ${group}.ChatManager
authors: [H1DD3NxN1NJA, Ryder Belserion]

version: ${version}
api-version: "1.18"
description: ${description}
website: ${website}

softdepend:
 - PlaceholderAPI
 - Vault
 - Essentials
 - SuperVanish
        
permissions:
    chatmanager.antiswear:
        description: Permission to view all the commands for the anti swear.
        default: op
    chatmanager.antiswear.help:
        description: Permission to view all the commands for the anti swear.
        default: op
    chatmanager.antiswear.add:
        description: Permission to add a word to the bannedwords.yml file.
        default: op
    chatmanager.antiswear.list:
        description: Permission to view a list of all the banned words.
        default: op
    chatmanager.antiswear.remove:
        description: Permission to remove a word from the bannedwords.yml file.
        default: op
    chatmanager.autobroadcast:
        description: Permission to view all the commands for auto broadcast.
        default: op
    chatmanager.autobroadcast.help:
        description: Permission to view all the commands for auto broadcast.
        default: op
    chatmanager.autobroadcast.list:
        description: Permission to view a list of all the auto broadcasts in a world.
        default: op
    chatmanager.autobroadcast.add:
        description: Permission to add new auto broadcast messages to the game.
        default: op
    chatmanager.autobroadcast.create:
        description: Permission to create new auto broadcast world to the game.
        default: op
    chatmanager.bannedcommands:
        description: Permission to view all the commands for banned commands.
        default: op
    chatmanager.bannedcommands.help:
        description: Permission to view all the commands for banned commands.
        default: op
    chatmanager.bannedcommands.add:
        description: Permission to add a command to the bannedcommands.yml file.
        default: op
    chatmanager.bannedcommands.list:
        description: Permission to view a list of all the banned commands.
        default: op
    chatmanager.bannedcommands.remove:
        description: Permission to remove a command from the bannedcommands.yml file.
        default: op
    chatmanager.announcement:
        description: Permission to use the command /announcement.
        default: op
    chatmanager.broadcast:
        description: Permission to use the command /broadcast.
        default: op
    chatmanager.colors:
        description: Permission to see a list of color codes.
        default: op
    chatmanager.chatradius:
        description: Permission to use chat radius.
        default: op
    chatmanager.chatradius.local:
        description: Permission to enable local chat.
        default: op
    chatmanager.chatradius.global:
        description: Permission to enable global chat.
        default: op
    chatmanager.chatradius.global.override:
        description: Permission to enable global chat with the override symbol.
        default: op
    chatmanager.chatradius.world:
        description: Permission to enable world chat.
        default: op
    chatmanager.chatradius.spy:
        description: Permission to enable chat radius spy.
        default: op
    chatmanager.clearchat:
        description: Permission to use the command /clearchat.
        default: op
    chatmanager.commandspy:
        description: Permission to use the command /commandspy.
        default: op
    chatmanager.debug:
        description: Permission to debug the plugin.
        default: op
    chatmanager.lists.players:
        description: Permission to use the command /list.
        default: op
    chatmanager.lists.staff:
        description: Permission to use the command /staff.
        default: op
    chatmanager.mention:
        description: Permission to send mention notifications to other players.
        default: op
    chatmanager.mention.receive:
      description: Permission to receive mention notifications
      default: op
    chatmanager.mention.everyone:
        description: Permission to send everyone mention notifications.
        default: op
    chatmanager.message:
        description: Permission to send private messages to other players on the server.
        default: op
    chatmanager.message.self:
        description: Permission to allow players to send themselves private messages.
        default: op
    chatmanager.mutechat:
        description: Permission to use the command /mutechat.
        default: op
    chatmanager.mutechat.silent:
        description: Permission to use the command /mutechat -s.
        default: op
    chatmanager.perworldchat:
        description: Permission to use the command /perworldchat.
        default: op
    chatmanager.preview.actionbar:
        description: Permission to show the join action bar
        default: op
    chatmanager.preview.title:
        description: Permission to show the join title.
        default: op
    chatmanager.reload:
        description: Permission to reload all the configuration files.
        default: op
    chatmanager.reply:
        description: Permission to reply to a private message.
        default: op
    chatmanager.rules:
        description: Permission to use the command /rules.
        default: true
    chatmanager.sign.color:
        description: Permission to use color codes on signs.
        default: op
    chatmanager.sign.formats:
        description: Permission to use format codes on signs.
        default: op
    chatmanager.socialspy:
        description: Permission to use the command /socialspy.
        default: op
    chatmanager.staffchat:
        description: Permission to use the command /staffchat.
        default: op
    chatmanager.toggle.chat:
        description: Permission to use the command /togglechat.
        default: op
    chatmanager.toggle.mentions:
        description: Permission to use the command /togglementions
        default: op
    chatmanager.toggle.pm:
        description: Permission to use the command /togglepm.
        default: op
    chatmanager.bypass.togglepm:
        description: Permission to send private messages to players even if they togglepm enabled.
        default: op
    chatmanager.warning:
        description: Permission to use the command /warning.
        default: op
    chatmanager.notify.antiadvertising:
        description: Permission to get notified when players advertise in chat.
        default: op
    chatmanager.notify.antiswear:
        description: Permission to get notified when a player swears in chat.
        default: op
    chatmanager.notify.antiunicode:
        description: Permission to get notified when a player uses special characters in chat.
        default: op
    chatmanager.notify.bannedcommands:
        description: Permission to get notified when a player uses a banned command.
        default: op
    chatmanager.bypass.afk:
        description: Permission to send private messages to players that are AFK.
        defualt: op
    chatmanager.bypass.antiadvertising:
        description: Permission to bypass the anti-advertising checker.
        default: op
    chatmanager.bypass.antibot:
        description: Permission to talk in chat without moving on join.
        default: op
    chatmanager.bypass.antiswear:
        description: Permission to bypass the anti-swear checker.
        default: op
    chatmanager.bypass.antiunicode:
        description: Permission to bypass the anti-unicode checker.
        default: op
    chatmanager.bypass.bannedcommands:
        description: Permission to bypass the banned commands checker.
        default: op
    chatmanager.bypass.caps:
        description: Permission to bypass caps checker.
        default: op
    chatmanager.bypass.chatdelay:
        description: Permission to bypass the chat delay.
        default: op
    chatmanager.bypass.chatradius:
        description: Permission to bypass the chat radius.
        default: op
    chatmanager.bypass.clearchat:
        description: Permission to bypass clear chat.
        default: op
    chatmanager.bypass.clearchat.onjoin:
        description: Permission to bypass clear chat on join.
        default: op
    chatmanager.bypass.coloncommands:
        description: Permission to use colons in commands.
        default: op
    chatmanager.bypass.commanddelay:
        description: Permission to bypass the command delay.
        default: op
    chatmanager.bypass.commandspy:
        description: Permission to bypass command spy.
        default: op
    chatmanager.bypass.dupe.chat:
        description: Permission to use repetitive messages.
        default: op
    chatmanager.bypass.dupe.command:
        description: Permission to use repetitive commands.
        default: op
    chatmanager.bypass.grammar:
        description: Permission to bypass the grammar checks.
        default: op
    chatmanager.bypass.ignored:
        description: Permission to be able to send private messages to players that are ignoring you.
        default: op
    chatmanager.bypass.mutechat:
        description: Permission to talk in chat when chat is disabled.
        default: op
    chatmanager.bypass.socialspy:
        description: Permission to bypass being seen from social spy.
        default: op
    chatmanager.bypass.spectator:
        description: Permission to private message staff that are in spectator mode.
        default: op
    chatmanager.bypass.vanish:
        description: Permission to send private messages to players that are in vanish.
        default: op
    chatmanager.formats.all:
        description: Permission to use all color and format codes in chat.
        default: op
    chatmanager.color.all:
        description: Permission to use all color codes in chat.
        default: op
    chatmanager.format.all:
        description: Permission to use all format codes in chat.
        default: op
    chatmanager.color.a:
        description: Permission to use the color code &a in chat.
        default: op
    chatmanager.color.b:
        description: Permission to use the color code &b in chat.
        default: op
    chatmanager.color.c:
        description: Permission to use the color code &c in chat.
        default: op
    chatmanager.color.d:
        description: Permission to use the color code &d in chat.
        default: op
    chatmanager.color.e:
        description: Permission to use the color code &e in chat.
        default: op
    chatmanager.color.f:
        description: Permission to use the color code &f in chat.
        default: op
    chatmanager.color.0:
        description: Permission to use the color code &0 in chat.
        default: op
    chatmanager.color.1:
        description: Permission to use the color code &1 in chat.
        default: op
    chatmanager.color.2:
        description: Permission to use the color code &2 in chat.
        default: op
    chatmanager.color.3:
        description: Permission to use the color code &3 in chat.
        default: op
    chatmanager.color.4:
        description: Permission to use the color code &4 in chat.
        default: op
    chatmanager.color.5:
        description: Permission to use the color code &5 in chat.
        default: op
    chatmanager.color.6:
        description: Permission to use the color code &6 in chat.
        default: op
    chatmanager.color.7:
        description: Permission to use the color code &7 in chat.
        default: op
    chatmanager.color.8:
        description: Permission to use the color code &8 in chat.
        default: op
    chatmanager.color.9:
        description: Permission to use the color code &9 in chat.
        default: op
    chatmanager.format.k:
        description: Permission to use the format code &k in chat.
        default: op
    chatmanager.format.l:
        description: Permission to use the format code &l in chat.
        default: op
    chatmanager.format.m:
        description: Permission to use the format code &m in chat.
        default: op
    chatmanager.format.n:
        description: Permission to use the format code &n in chat.
        default: op
    chatmanager.format.o:
        description: Permission to use the format code &o in chat.
        default: op
    chatmanager.format.r:
        description: Permission to use the format code &r in chat.
        default: op
    chatmanager.chatradius.all:
        description: Permission to access all chat radius channels.
        default: false
        children:
            chatmanager.chatradius: true
            chatmanager.chatradius.local: true
            chatmanager.chatradius.global: true
            chatmanager.chatradius.global.override: true
            chatmanager.chatradius.world: true
            chatmanager.chatradius.spy: true
    chatmanager.bypass.all:
        description: Give players access to bypass every check.
        default: false
        children:
            chatmanager.bypass.afk: true
            chatmanager.bypass.antiadvertising: true
            chatmanager.bypass.antibot: true
            chatmanager.bypass.antiswear: true
            chatmanager.bypass.antiunicode: true
            chatmanager.bypass.bannedcommands: true
            chatmanager.bypass.caps: true
            chatmanager.bypass.chatdelay: true
            chatmanager.bypass.chatradius: true
            chatmanager.bypass.clearchat: true
            chatmanager.bypass.clearchat.onjoin: true
            chatmanager.bypass.coloncommands: true
            chatmanager.bypass.commanddelay: true
            chatmanager.bypass.commandspy: true
            chatmanager.bypass.dupe.chat: true
            chatmanager.bypass.dupe.command: true
            chatmanager.bypass.grammar: true
            chatmanager.bypass.ignored: true
            chatmanager.bypass.mutechat: true
            chatmanager.bypass.socialspy: true
            chatmanager.bypass.spectator: true
            chatmanager.bypass.togglepm: true
            chatmanager.bypass.vanish: true
    chatmanager.commands.all:
        description: Give players access to every command.
        default: false
        children:
            chatmanager.antiswear: true
            chatmanager.antiswear.help: true
            chatmanager.antiswear.add: true
            chatmanager.antiswear.list: true
            chatmanager.antiswear.remove: true
            chatmanager.autobroadcast: true
            chatmanager.autobroadcast.help: true
            chatmanager.autobroadcast.add: true
            chatmanager.autobroadcast.create: true
            chatmanager.autobroadcast.list: true
            chatmanager.bannedcommands: true
            chatmanager.bannedcommands.help: true
            chatmanager.bannedcommands.add: true
            chatmanager.bannedcommands.list: true
            chatmanager.bannedcommands.remove: true
            chatmanager.announcement: true
            chatmanager.broadcast: true
            chatmanager.chatradius: true
            chatmanager.chatradius.local: true
            chatmanager.chatradius.global: true
            chatmanager.chatradius.world: true
            chatmanager.chatradius.spy: true
            chatmanager.clearchat: true
            chatmanager.colors: true
            chatmanager.commandspy: true
            chatmanager.debug: true
            chatmanager.formats: true
            chatmanager.lists.players: true
            chatmanager.lists.staff: true
            chatmanager.message: true
            chatmanager.message.self: true
            chatmanager.mutechat: true
            chatmanager.mutechat.silent: true
            chatmanager.perworldchat: true
            chatmanager.preview.title: true
            chatmanager.preview.actionbar: true
            chatmanager.reload: true
            chatmanager.reply: true
            chatmanager.rules: true
            chatmanager.socialspy: true
            chatmanager.staffchat: true
            chatmanager.togglechat: true
            chatmanager.togglepm: true
            chatmanager.warning: true
    chatmanager.notify.all:
        description: Gets notified everytime a player breaks the rules.
        default: false
        children:
            chatmanager.notify.antiadvertising: true
            chatmanager.notify.antiswear: true
            chatmanager.notify.antiunicode: true
            chatmanager.notify.bannedcommands: true
    chatmanager.*:
        description: Give players with op everything by default.
        default: op
        children:
            chatmanager.bypass.all: true
            chatmanager.commands.all: true
            chatmanager.chatradius.all: true
            chatmanager.notify.all: true
            chatmanager.formats.all: true
            chatmanager.global.chatradius: true
            chatmanager.privatemessage.self: true