[versions]

github = "https://github.com/Crazy-Crew/ChatManager"
beta = "true"
extension = "plugin"

[plugins]

minotaur = { id = "com.modrinth.minotaur", version = "2.7.2" }
run-paper = { id = "xyz.jpenilla.run-paper", version = "2.0.1" }