name: '${name}'
main: '${group}.${name}'
loader: '${group}.loader.ChatManagerLoader'

version: '${version}'
api-version: '${apiVersion}'
description: '${description}'
website: '${website}'

folia-supported: true

dependencies:
  server:
    PlaceholderAPI:
     load: BEFORE
     required: false
     join-classpath: true