name: Release
on:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Read Version Catalog
        uses: SebRollen/toml-action@v1.2.0
        id: chatmanager_version
        with:
          file: "gradle/libs.versions.toml"
          field: "versions.chatmanager"
      - name: Build
        run: ./gradlew build --stacktrace
      - name: Publish to Modrinth
        run: ./gradlew modrinth --stacktrace
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}