name: '${name}'
main: '${group}.${name}'

version: '${version}'
api-version: '${apiVersion}'
description: '${description}'
website: '${website}'

folia-supported: true

authors: [ h1dd3nxn1nja, ryderbelserion ]

dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false
      join-classpath: true
    SuperVanish:
      load: BEFORE
      required: false
      join-classpath: true
    Essentials:
      load: BEFORE
      required: false
      join-classpath: true
    Vault:
      load: BEFORE
      required: false
      join-classpath: true