name: '${name}'
main: '${group}.${name}'

version: '${version}'
api-version: '${minecraft}'
description: '${description}'

folia-supported: true

dependencies:
  server:
    PlaceholderAPI:
     load: BEFORE
     required: false
     join-classpath: true