name: '${name}'
main: '${group}.ChatManagerPlugin'

version: '${version}'
api-version: '${minecraft}'
description: '${description}'

folia-supported: true

dependencies:
  server:
    PlaceholderAPI:
     load: BEFORE
     required: false
     join-classpath: true
    HeadDatabase:
      load: BEFORE
      required: false
      join-classpath: true